/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Classes.Estoque;
import javax.swing.DefaultListModel;

/**
 *
 * @author Vinicius
 */
public class frmEstoque extends javax.swing.JInternalFrame {

    private Estoque estoque = new Estoque();
     private DefaultListModel lista = new DefaultListModel();
     
    /** Creates new form frmEstoque */
    public frmEstoque() {
        initComponents();
        listaProdutos.setModel(lista);
        atualizar();
    }
    
    public void atualizar() {
        lista.clear();
        for(int i = 0; i < estoque.getDados().length; i++) {
            if(estoque.getDados()[i][0] != null) {
                lista.addElement("Nome: " + estoque.getDados()[i][0] + " | Valor: " + estoque.getDados()[i][1] + " | Quantidade: " + estoque.getDados()[i][2]);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        inpProduto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        inpValor = new javax.swing.JTextField();
        inpQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(listaProdutos);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inpProduto))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(inpValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String[][] dados = estoque.getDados();
        
        String produto = inpProduto.getText();
        int quantidade = Integer.valueOf(inpQuantidade.getText());
        double valor = Double.valueOf(inpValor.getText());
        
        boolean produtoExiste = false;
        for(int i = 0; i < dados.length; i++) {
            if(estoque.getDados()[i][0] != null && dados[i][0].equals(produto)) {
                produtoExiste = true;
            }
        }
        
        if(produtoExiste) {
            for(int i = 0; i < dados.length; i++) {
                if(estoque.getDados()[i][0] != null && dados[i][0].equals(produto)) {
                    dados[i][1] = String.valueOf(valor);
                    dados[i][2] = String.valueOf(Integer.valueOf(dados[i][2]) + quantidade);
                }
            }
        } else {
            int indiceNaoExiste = -1;
            for(int i = 0; i < dados.length; i++) {
                if(indiceNaoExiste == -1 && estoque.getDados()[i][0] == null) {
                    indiceNaoExiste = i;
                }
            }
            dados[indiceNaoExiste][0] = produto;
            dados[indiceNaoExiste][1] = String.valueOf(valor);
            dados[indiceNaoExiste][2] = String.valueOf(quantidade);
        }
        
        estoque.setDados(dados);
        atualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String[][] dados = estoque.getDados();
        
        String produto = inpProduto.getText();
        int quantidade = Integer.valueOf(inpQuantidade.getText());
        double valor = Double.valueOf(inpValor.getText());
        
        boolean produtoExiste = false;
        for(int i = 0; i < dados.length; i++) {
            if(estoque.getDados()[i][0] != null && dados[i][0].equals(produto)) {
                produtoExiste = true;
            }
        }
        
        if(produtoExiste) {
            for(int i = 0; i < dados.length; i++) {
                if(estoque.getDados()[i][0] != null && dados[i][0].equals(produto)) {
                    
                    if(Double.valueOf(dados[i][2]) >= quantidade) {
                        dados[i][1] = String.valueOf(valor);
                        dados[i][2] = String.valueOf(Integer.valueOf(dados[i][2]) - quantidade);
                    } else {
                        dados[i][0] = null;
                        dados[i][1] = null;
                        dados[i][2] = null;
                    }
                }
            }
        }
        
        estoque.setDados(dados);
        atualizar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inpProduto;
    private javax.swing.JTextField inpQuantidade;
    private javax.swing.JTextField inpValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaProdutos;
    // End of variables declaration//GEN-END:variables

}
